# Generated by Django 3.1.1 on 2021-03-31 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=50)),
                ('numero_rg', models.CharField(max_length=15)),
                ('numero_cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=25)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero_residencia', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('naturalidade', models.CharField(max_length=50)),
                ('activate', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=50)),
                ('extra_field1', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_field2', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_field3', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_field4', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.FileField(blank=True, null=True, upload_to='')),
                ('file_ok', models.BooleanField(default=None)),
                ('id_cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api_ATT.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Dossie',
            fields=[
                ('id_dossie', models.AutoField(primary_key=True, serialize=False)),
                ('flag_cadastro_completo', models.BooleanField(blank=True, null=True)),
                ('flag_copia_rg_cnh', models.BooleanField(blank=True, null=True)),
                ('flag_comprovante_endereco', models.BooleanField(blank=True, null=True)),
                ('flag_comprovante_ocupacao', models.BooleanField(blank=True, null=True)),
                ('flag_certidao_federal', models.BooleanField(blank=True, null=True)),
                ('flag_certidao_estadual', models.BooleanField(blank=True, null=True)),
                ('flag_certidao_militar', models.BooleanField(blank=True, null=True)),
                ('flag_certidao_eleitoral', models.BooleanField(blank=True, null=True)),
                ('flag_requerimento_comandante', models.BooleanField(blank=True, null=True)),
                ('flag_declaracao_antecedentes', models.BooleanField(blank=True, null=True)),
                ('flag_declaracao_seguranca_acervo', models.BooleanField(blank=True, null=True)),
                ('flag_declaracao_endereco_acervo', models.BooleanField(blank=True, null=True)),
                ('flag_termo_ciencia_compromisso', models.BooleanField(blank=True, null=True)),
                ('flag_laudo_psicologico', models.BooleanField(blank=True, null=True)),
                ('flag_laudo_tecnico', models.BooleanField(blank=True, null=True)),
                ('flag_filiacao', models.BooleanField(blank=True, null=True)),
                ('flag_comprovante_pagamento_gru', models.BooleanField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='dossies', to='api_ATT.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_etapa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PreCliente',
            fields=[
                ('id_pre_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=50)),
                ('numero_rg', models.CharField(max_length=15)),
                ('numero_cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=25)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero_residencia', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('naturalidade', models.CharField(max_length=50)),
                ('emprego_fixo', models.BooleanField()),
                ('possui_antecedentes', models.BooleanField()),
                ('ciente_das_validacoes', models.BooleanField()),
                ('activate', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ['id_pre_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id_protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('num_protocolo', models.IntegerField()),
                ('dt_protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('subsecao', models.CharField(blank=True, max_length=50, null=True)),
                ('servico', models.CharField(blank=True, max_length=100, null=True)),
                ('id_dossie', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='api_ATT.dossie')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_documento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id_tipo_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pagamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('num_recibo', models.IntegerField()),
                ('dt_emissao_recibo', models.DateField(default=django.utils.timezone.now)),
                ('vl_recibo', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ATT.cliente')),
                ('id_tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ATT.tipopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_aviso', models.DateTimeField(blank=True, null=True)),
                ('mensagens', models.CharField(blank=True, max_length=50, null=True)),
                ('ciencia_registrada', models.CharField(blank=True, max_length=50, null=True)),
                ('protocolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='api_ATT.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesExtraCliente',
            fields=[
                ('id_informacao_extra', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pai', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_extras', to='api_ATT.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSalvos',
            fields=[
                ('id_file_salve', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ATT.cliente')),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_id', to='api_ATT.documento')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='id_tipo_documento',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_documento', to='api_ATT.tipodocumento'),
        ),
    ]
